"""allow duplicate urls for soft deleted websites

Revision ID: 6fe1b02a8be4
Revises: de717b7e58a7
Create Date: 2026-08-31 19:11:05.006290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe1b02a8be4'
down_revision: Union[str, Sequence[str], None] = 'de717b7e58a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('website_url_key'), 'website', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('website_url_key'), 'website', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
