"""create health check table

Revision ID: 9fc5f22aa264
Revises: 6fe1b02a8be4
Create Date: 2026-09-04 18:12:34.603453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc5f22aa264'
down_revision: Union[str, Sequence[str], None] = '6fe1b02a8be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_check_website_id', 'health_check', ['website_id'], unique=False)
    op.create_index('uq_website_url_active', 'website', ['url'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_website_url_active', table_name='website', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_health_check_website_id', table_name='health_check')
    op.drop_table('health_check')
    # ### end Alembic commands ###
